name: Laravel-wrapped-package-test

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install host app
      run: composer create-project --prefer-dist laravel/laravel host
    - name: Install package (this repo)
      uses: actions/checkout@v2
      with:
        path: packages/Ajthinking/PHPFileManipulator
    - name: Add the repo to composer.json
      uses: ajthinking/merge-json-files@v1.0.15
      with:
        repo_relative_path: 'packages/Ajthinking/PHPFileManipulator'
    - name: Require the package
      working-directory: src
      run: composer require ajthinking/php-file-manipulator @dev
    - name: Publish things
      run: php artisan vendor:publish --provider="PHPFileManipulator\ServiceProvider"
    - name: Run tests
      run: vendor/phpunit/phpunit/phpunit packages/Ajthinking/PHPFileManipulator/tests
