name: tests

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install a containing host app
      run: composer create-project --prefer-dist laravel/laravel host
      
    - name: Checkout the package - this repo - into a packages folder
      uses: actions/checkout@v2
      with:
        path: host/packages/Ajthinking/PHPFileManipulator

    - name: Add the package to host composer.json repositories
      run: composer config repositories.php-file-manipulator path "/home/runner/work/php-file-manipulator/php-file-manipulator/host/packages/Ajthinking/PHPFileManipulator"

    - name: Require this package
      working-directory: ./host
      run: composer require ajthinking/php-file-manipulator @dev

    - name: Publish things
      working-directory: ./host
      run: php artisan vendor:publish --provider="PHPFileManipulator\ServiceProvider"

    - name: Run tests
      working-directory: ./host      
      run: vendor/phpunit/phpunit/phpunit packages/Ajthinking/PHPFileManipulator/tests
